mybatis-plus:
  mapper-locations: classpath*:/mapper/null/**Mapper.xml  #Mapper文件位置
  type-aliases-package: com.jiang.back.entity  #实体类位置
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰
    use-generated-keys: true #使用主键

#spring配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

server:
  port: 8888
